name: sonatype-deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt
          java-version: 8
      - name: Build with Maven
        run: mvn -B install
      - name: Nexus Repo Publish
        run: |
          gpg --quiet \
            --batch \
            --yes \
            --decrypt \
            --passphrase="${{ secrets.GPG_PASSPHRASE }}" \
            --output codesigning.asc \
            .github/codesigning.asc.gpg
          gpg --batch \
            --fast-import codesigning.asc
          mvn --settings .github/settings.xml \
            -Dskip-Tests=true \
            -P release \
            -B \
            deploy
        env:
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Publish Javadoc
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: target/apidocs # The folder the action should deploy.
